import { $ } from "bun";
import path from "path";

const ROOT = path.join(import.meta.dirname, "..");

/** Parse a .env file into a Map, preserving order isn't needed since we rewrite */
function parseEnv(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    map.set(trimmed.slice(0, eqIndex), trimmed.slice(eqIndex + 1));
  }
  return map;
}

async function main() {
  const output = await $`supabase status -o json`.cwd(ROOT).text();
  const status = JSON.parse(output);

  const dbUrl = status.DB_URL;
  const apiUrl = status.API_URL;
  const anonKey = status.ANON_KEY;
  const serviceRoleKey = status.SERVICE_ROLE_KEY;

  if (!dbUrl || !apiUrl || !serviceRoleKey) {
    console.error("Supabase is not running. Run `supabase start` first.");
    process.exit(1);
  }

  // --- Worker .env ---
  const workerEnvPath = path.join(ROOT, "apps/worker/.env");
  const existingWorker = await Bun.file(workerEnvPath)
    .text()
    .catch(() => "");
  const workerVars = parseEnv(existingWorker);

  // Supabase-derived (always overwrite)
  workerVars.set("DATABASE_URL", dbUrl);
  workerVars.set("SUPABASE_URL", apiUrl);
  workerVars.set("SUPABASE_SERVICE_ROLE_KEY", serviceRoleKey);

  // Defaults (only set if missing)
  if (!workerVars.has("HEALTH_PORT")) workerVars.set("HEALTH_PORT", "9090");
  if (!workerVars.has("BULL_BOARD_PORT"))
    workerVars.set("BULL_BOARD_PORT", "9091");
  if (!workerVars.has("METRICS_PORT")) workerVars.set("METRICS_PORT", "9092");
  if (!workerVars.has("LOG_LEVEL")) workerVars.set("LOG_LEVEL", "info");
  if (!workerVars.has("SLACK_WEBHOOK_URL"))
    workerVars.set("SLACK_WEBHOOK_URL", "");

  const workerEnv = `# Auto-generated by scripts/gen-env.ts
# Supabase-derived values are overwritten on each run.
# All other values are preserved — safe to edit manually.
${[...workerVars].map(([k, v]) => `${k}=${v}`).join("\n")}
`;
  await Bun.write(workerEnvPath, workerEnv);
  console.log("  apps/worker/.env");

  // --- Web .env.local ---
  const webDir = path.join(ROOT, "apps/web");
  const webExists = await Bun.file(path.join(webDir, "package.json")).exists();
  if (webExists) {
    const webEnvPath = path.join(webDir, ".env.local");
    const existingWeb = await Bun.file(webEnvPath)
      .text()
      .catch(() => "");
    const webVars = parseEnv(existingWeb);

    // Supabase-derived (always overwrite)
    webVars.set("NEXT_PUBLIC_SUPABASE_URL", apiUrl);
    webVars.set("NEXT_PUBLIC_SUPABASE_ANON_KEY", anonKey);
    webVars.set("SUPABASE_SERVICE_ROLE_KEY", serviceRoleKey);
    webVars.set("DATABASE_URL", dbUrl);

    // Defaults (only set if missing — never overwrite manual values)
    if (!webVars.has("REDIS_HOST")) webVars.set("REDIS_HOST", "127.0.0.1");
    if (!webVars.has("REDIS_PORT")) webVars.set("REDIS_PORT", "6379");
    if (!webVars.has("GOOGLE_CLIENT_ID")) webVars.set("GOOGLE_CLIENT_ID", "");
    if (!webVars.has("GOOGLE_CLIENT_SECRET"))
      webVars.set("GOOGLE_CLIENT_SECRET", "");

    // Sentry
    if (!webVars.has("NEXT_PUBLIC_SENTRY_DSN"))
      webVars.set("NEXT_PUBLIC_SENTRY_DSN", "");
    if (!webVars.has("SENTRY_DSN")) webVars.set("SENTRY_DSN", "");
    if (!webVars.has("SENTRY_ORG")) webVars.set("SENTRY_ORG", "");
    if (!webVars.has("SENTRY_PROJECT")) webVars.set("SENTRY_PROJECT", "");
    if (!webVars.has("SENTRY_AUTH_TOKEN"))
      webVars.set("SENTRY_AUTH_TOKEN", "");

    // PostHog
    if (!webVars.has("NEXT_PUBLIC_POSTHOG_KEY"))
      webVars.set("NEXT_PUBLIC_POSTHOG_KEY", "");
    if (!webVars.has("NEXT_PUBLIC_POSTHOG_HOST"))
      webVars.set("NEXT_PUBLIC_POSTHOG_HOST", "https://us.i.posthog.com");

    // Microsoft Clarity
    if (!webVars.has("NEXT_PUBLIC_CLARITY_PROJECT_ID"))
      webVars.set("NEXT_PUBLIC_CLARITY_PROJECT_ID", "");

    const webEnv = `# Auto-generated by scripts/gen-env.ts
# Supabase-derived values are overwritten on each run.
# All other values are preserved — safe to edit manually.
${[...webVars].map(([k, v]) => `${k}=${v}`).join("\n")}
`;
    await Bun.write(webEnvPath, webEnv);
    console.log("  apps/web/.env.local");
  }

  console.log("\nDone. Env files written from running Supabase instance.");
}

main();
